<a href="https://colab.research.google.com/github/SEBASTIANVALDIVIESO/PRODUCTO_DATOS/blob/main/01_RECOLECCION_Y_ORGANIZACION_DE_DATOS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. RECOLECCION Y ORGANIZACION DE DATOS**

**- CARGA DEL DATASET**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import drive

drive.mount('/content/drive')

%cd /content/drive/MyDrive/Notebooks_Clase_2/content/producto_de_datos

Mounted at /content/drive
/content/drive/MyDrive/Notebooks_Clase_2/content/producto_de_datos

In [ ]:
# Ruta completa del archivo CSV
file_path = '/content/drive/MyDrive/Notebooks_Clase_2/content/producto_de_datos/internet_fijo.csv'

df = pd.read_csv(file_path)

In [ ]:
df.head()

,AÑO,TRIMESTRE,PROVEEDOR,COD_DEPARTAMENTO,DEPARTAMENTO,COD_MUNICIPIO,MUNICIPIO,SEGMENTO,TECNOLOGIA,VELOCIDAD_BAJADA,VELOCIDAD_SUBIDA,No DE ACCESOS
0,2023,2,DIRECTV COLOMBIA LTDA,8.0,ATLÁNTICO,8520.0,PALMAR DE VARELA,RESIDENCIAL - ESTRATO 1,OTRAS TECNOLOGÍAS INALÁMBRICAS,"6,00","1,00",3
1,2021,2,COCOM S.A.S,63.0,QUINDÍO,63272.0,FILANDIA,RESIDENCIAL - ESTRATO 2,WIFI,"5,00","5,00",1
2,2021,1,COMUNICACION CELULAR S A COMCEL S A,8.0,ATLÁNTICO,8001.0,BARRANQUILLA,RESIDENCIAL - ESTRATO 2,CABLE,"10,00","5,00",43
3,2021,3,COLOMBIA TELECOMUNICACIONES S.A. E.S.P.,76.0,VALLE DEL CAUCA,76001.0,CALI,RESIDENCIAL - ESTRATO 5,OTRAS TECNOLOGÍAS DE FIBRA (ANTES FTTX),"15,00","1,00",16
4,2023,3,DIFUDATOS S A S,25.0,CUNDINAMARCA,25224.0,CUCUNUBÁ,CORPORATIVO,OTRAS TECNOLOGÍAS INALÁMBRICAS,"30,00","24,00",1

**VALORES NULOS O FALTANTES**

In [ ]:
print(df.duplicated().sum())

90699

In [ ]:
#Elimina duplicados:

df = df.drop_duplicates()
print(df.duplicated().sum())

0

In [ ]:
# Eliminar filas con valores nulos en las columnas específicas
df = df.dropna(subset=['COD_DEPARTAMENTO', 'COD_MUNICIPIO'])

# Verificar si las filas fueron eliminadas
print(df.isnull().sum())

AÑO                 0
TRIMESTRE           0
PROVEEDOR           0
COD_DEPARTAMENTO    0
DEPARTAMENTO        0
COD_MUNICIPIO       0
MUNICIPIO           0
SEGMENTO            0
TECNOLOGIA          0
VELOCIDAD_BAJADA    0
VELOCIDAD_SUBIDA    0
No DE ACCESOS       0
dtype: int64

**VALORES DUPLICADOS**

In [ ]:
# Listado de columnas y datos faltantes en cada una.

for i in df.columns:
    print ("%20s"%i, np.sum(df[i].isna()))

                 AÑO 0
           TRIMESTRE 0
           PROVEEDOR 0
    COD_DEPARTAMENTO 0
        DEPARTAMENTO 0
       COD_MUNICIPIO 0
           MUNICIPIO 0
            SEGMENTO 0
          TECNOLOGIA 0
    VELOCIDAD_BAJADA 0
    VELOCIDAD_SUBIDA 0
       No DE ACCESOS 0

In [ ]:
# Verificar si existen valores nulos y cuántos
df.isnull().sum()

AÑO                 0
TRIMESTRE           0
PROVEEDOR           0
COD_DEPARTAMENTO    0
DEPARTAMENTO        0
COD_MUNICIPIO       0
MUNICIPIO           0
SEGMENTO            0
TECNOLOGIA          0
VELOCIDAD_BAJADA    0
VELOCIDAD_SUBIDA    0
No DE ACCESOS       0
dtype: int64

**CORRECION DE NOMBRE DE COLUMNAS O VARIABLES**

In [ ]:
# Diccionario para asignar la fecha de fin de trimestre
ftrimestre = {
    1: '-03-31',
    2: '-06-30',
    3: '-09-30',
    4: '-12-31'
}

# Columna nueva de Fecha Unifica el ultimo dia de cada trimestre
df['FECHA'] = df['AÑO'].astype(str) + df['TRIMESTRE'].map(ftrimestre)

# Fecha a Datatime
df['FECHA'] = pd.to_datetime(df['FECHA'])

# Eliminar las columnas Año y Trimestre
df = df.drop(['AÑO', 'TRIMESTRE'], axis=1)


#Ordena la variable Fecha de primero
cols = ['FECHA'] + [col for col in df.columns if col != 'FECHA']
df = df[cols]

df.columns

Index(['FECHA', 'PROVEEDOR', 'COD_DEPARTAMENTO', 'DEPARTAMENTO',
       'COD_MUNICIPIO', 'MUNICIPIO', 'SEGMENTO', 'TECNOLOGIA',
       'VELOCIDAD_BAJADA', 'VELOCIDAD_SUBIDA', 'No DE ACCESOS'],
      dtype='object')

In [ ]:
# Verificar el resultado
print(df.head())

       FECHA                                PROVEEDOR  COD_DEPARTAMENTO  \
0 2023-06-30                    DIRECTV COLOMBIA LTDA               8.0
1 2021-06-30                              COCOM S.A.S              63.0
2 2021-03-31      COMUNICACION CELULAR S A COMCEL S A               8.0
3 2021-09-30  COLOMBIA TELECOMUNICACIONES S.A. E.S.P.              76.0
4 2023-09-30                          DIFUDATOS S A S              25.0

      DEPARTAMENTO  COD_MUNICIPIO         MUNICIPIO                 SEGMENTO  \
0        ATLÁNTICO         8520.0  PALMAR DE VARELA  RESIDENCIAL - ESTRATO 1
1          QUINDÍO        63272.0          FILANDIA  RESIDENCIAL - ESTRATO 2
2        ATLÁNTICO         8001.0      BARRANQUILLA  RESIDENCIAL - ESTRATO 2
3  VALLE DEL CAUCA        76001.0              CALI  RESIDENCIAL - ESTRATO 5
4     CUNDINAMARCA        25224.0          CUCUNUBÁ              CORPORATIVO

                                TECNOLOGIA VELOCIDAD_BAJADA VELOCIDAD_SUBIDA  \
0           OTRAS TECNOLOGÍAS INALÁMBRICAS             6,00             1,00
1                                     WIFI             5,00             5,00
2                                    CABLE            10,00             5,00
3  OTRAS TECNOLOGÍAS DE FIBRA (ANTES FTTX)            15,00             1,00
4           OTRAS TECNOLOGÍAS INALÁMBRICAS            30,00            24,00

   No DE ACCESOS
0              3
1              1
2             43
3             16
4              1

In [ ]:
df.rename(columns={'No DE ACCESOS': 'SUSCRIPTORES'}, inplace=True)

df.columns

Index(['FECHA', 'PROVEEDOR', 'COD_DEPARTAMENTO', 'DEPARTAMENTO',
       'COD_MUNICIPIO', 'MUNICIPIO', 'SEGMENTO', 'TECNOLOGIA',
       'VELOCIDAD_BAJADA', 'VELOCIDAD_SUBIDA', 'SUSCRIPTORES'],
      dtype='object')

In [ ]:
#crear un diccionario con la asignación de tecnologías generales
tech_mapping = {
    'FIBER TO THE HOME (FTTH)': 'FIBRA_OPTICA',
    'FIBER TO THE PREMISES': 'FIBRA_OPTICA',
    'FIBER TO THE BUILDING O FIBER TO THE BASEMENT (FTTB)': 'FIBRA_OPTICA',
    'FIBER TO THE NODE (FTTN)': 'FIBRA_OPTICA',
    'FIBER TO THE CABINET (FTTC)': 'FIBRA_OPTICA',
    'OTRAS TECNOLOGÍAS DE FIBRA (ANTES FTTX)': 'FIBRA_OPTICA',
    'CABLE': 'TECNOLOGIA_FIJA',
    'XDSL': 'TECNOLOGIA_FIJA',
    'OTRAS TECNOLOGÍAS INALÁMBRICAS': 'TECNOLOGIA_INALAMBRICA',
    'WIFI': 'TECNOLOGIA_INALAMBRICA',
    'SATELITAL': 'TECNOLOGIA_INALAMBRICA',
    'WIMAX': 'TECNOLOGIA_INALAMBRICA',
    'HYBRID FIBER COAXIAL (HFC)': 'HIBRIDA',
    'OTRAS TECNOLOGÍAS FIJAS': 'OTRAS_TECNOLOGIAS',
    'NA (NO APLICA)': 'OTRAS_TECNOLOGIAS'
}

# Reemplazar las tecnologías con las categorías generales
df['TECNOLOGIA'] = df['TECNOLOGIA'].map(tech_mapping)

# Verificar la nueva categorización
print(df['TECNOLOGIA'].value_counts())

TECNOLOGIA
TECNOLOGIA_FIJA           1089969
FIBRA_OPTICA               823711
TECNOLOGIA_INALAMBRICA     578063
HIBRIDA                    202831
OTRAS_TECNOLOGIAS            7175
Name: count, dtype: int64

In [ ]:
# Diccionario de renombrado
renaming_dict = {
    'CORPORATIVO': 'CORPORATIVO',
    'RESIDENCIAL - ESTRATO 1': 'RESIDENCIAL_ESTRATO1',
    'RESIDENCIAL - ESTRATO 2': 'RESIDENCIAL_ESTRATO2',
    'RESIDENCIAL - ESTRATO 3': 'RESIDENCIAL_ESTRATO3',
    'RESIDENCIAL - ESTRATO 4': 'RESIDENCIAL_ESTRATO4',
    'RESIDENCIAL - ESTRATO 5': 'RESIDENCIAL_ESTRATO5',
    'RESIDENCIAL - ESTRATO 6': 'RESIDENCIAL_ESTRATO6',
    'SIN ESTRATIFICAR': 'SIN_ESTRATIFICAR',
    'USO PROPIO INTERNO DEL OPERADOR': 'USO_PROPIO_INTERNO_DEL_OPERADOR'
}

# Reemplazar los valores en la columna 'SEGMENTO'
df['SEGMENTO'] = df['SEGMENTO'].replace(renaming_dict)

# Verificar los cambios
print(df['SEGMENTO'].value_counts())

SEGMENTO
CORPORATIVO                        874906
RESIDENCIAL_ESTRATO2               574685
RESIDENCIAL_ESTRATO3               405835
RESIDENCIAL_ESTRATO1               404909
RESIDENCIAL_ESTRATO4               213923
RESIDENCIAL_ESTRATO5               104359
RESIDENCIAL_ESTRATO6                81506
SIN_ESTRATIFICAR                    38137
USO_PROPIO_INTERNO_DEL_OPERADOR      6083
Name: count, dtype: int64

**CORRECCIÓN DE TIPO DE DATOS**

In [ ]:
# Verificar los valores únicos de una columna categórica
df['VELOCIDAD_BAJADA'].unique()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2704343 entries, 0 to 2795051
Data columns (total 11 columns):
 #   Column            Dtype
---  ------            -----
 0   FECHA             datetime64[ns]
 1   PROVEEDOR         object
 2   COD_DEPARTAMENTO  float64
 3   DEPARTAMENTO      object
 4   COD_MUNICIPIO     float64
 5   MUNICIPIO         object
 6   SEGMENTO          object
 7   TECNOLOGIA        object
 8   VELOCIDAD_BAJADA  object
 9   VELOCIDAD_SUBIDA  object
 10  SUSCRIPTORES      int64
dtypes: datetime64[ns](1), float64(2), int64(1), object(7)
memory usage: 247.6+ MB

In [ ]:
# Reemplazar las comas por puntos
df['VELOCIDAD_BAJADA'] = df['VELOCIDAD_BAJADA'].str.replace(',', '.')

df['VELOCIDAD_SUBIDA'] = df['VELOCIDAD_SUBIDA'].str.replace(',', '.')

# Convertir a tipo numérico (flotante)
df['VELOCIDAD_BAJADA'] = pd.to_numeric(df['VELOCIDAD_BAJADA'], errors='coerce')
df['VELOCIDAD_SUBIDA'] = pd.to_numeric(df['VELOCIDAD_SUBIDA'], errors='coerce')

# Si deseas convertir a enteros, puedes hacerlo después de asegurarte que los datos son válidos
df['VELOCIDAD_BAJADA'] = df['VELOCIDAD_BAJADA'].fillna(0).astype(int)
df['VELOCIDAD_SUBIDA'] = df['VELOCIDAD_SUBIDA'].fillna(0).astype(int)

df.dtypes

FECHA               datetime64[ns]
PROVEEDOR                   object
COD_DEPARTAMENTO           float64
DEPARTAMENTO                object
COD_MUNICIPIO              float64
MUNICIPIO                   object
SEGMENTO                    object
TECNOLOGIA                  object
VELOCIDAD_BAJADA             int64
VELOCIDAD_SUBIDA             int64
SUSCRIPTORES                 int64
dtype: object

In [ ]:
df

,FECHA,PROVEEDOR,COD_DEPARTAMENTO,DEPARTAMENTO,COD_MUNICIPIO,MUNICIPIO,SEGMENTO,TECNOLOGIA,VELOCIDAD_BAJADA,VELOCIDAD_SUBIDA,SUSCRIPTORES
0,2023-06-30,DIRECTV COLOMBIA LTDA,8.0,ATLÁNTICO,8520.0,PALMAR DE VARELA,RESIDENCIAL_ESTRATO1,TECNOLOGIA_INALAMBRICA,6,1,3
1,2021-06-30,COCOM S.A.S,63.0,QUINDÍO,63272.0,FILANDIA,RESIDENCIAL_ESTRATO2,TECNOLOGIA_INALAMBRICA,5,5,1
2,2021-03-31,COMUNICACION CELULAR S A COMCEL S A,8.0,ATLÁNTICO,8001.0,BARRANQUILLA,RESIDENCIAL_ESTRATO2,TECNOLOGIA_FIJA,10,5,43
3,2021-09-30,COLOMBIA TELECOMUNICACIONES S.A. E.S.P.,76.0,VALLE DEL CAUCA,76001.0,CALI,RESIDENCIAL_ESTRATO5,FIBRA_OPTICA,15,1,16
4,2023-09-30,DIFUDATOS S A S,25.0,CUNDINAMARCA,25224.0,CUCUNUBÁ,CORPORATIVO,TECNOLOGIA_INALAMBRICA,30,24,1
...,...,...,...,...,...,...,...,...,...,...,...
2795047,2020-12-31,EDATEL S.A.,5.0,ANTIOQUIA,5347.0,HELICONIA,RESIDENCIAL_ESTRATO2,TECNOLOGIA_FIJA,4,1,2
2795048,2019-09-30,EMPRESA DE TELECOMUNICACIONES DE BUCARAMANGA S...,68.0,SANTANDER,68547.0,PIEDECUESTA,RESIDENCIAL_ESTRATO3,TECNOLOGIA_FIJA,10,1,8
2795049,2017-12-31,COLOMBIA TELECOMUNICACIONES S.A. E.S.P.,54.0,NORTE DE SANTANDER,54001.0,SAN JOSÉ DE CÚCUTA,RESIDENCIAL_ESTRATO5,TECNOLOGIA_FIJA,7,1,20
2795050,2019-06-30,COLOMBIA TELECOMUNICACIONES S.A. E.S.P.,88.0,"ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANT...",88001.0,SAN ANDRÉS,RESIDENCIAL_ESTRATO4,TECNOLOGIA_FIJA,1,1,108
2795051,2019-12-31,COMUNICACION CELULAR S A COMCEL S A,25.0,CUNDINAMARCA,25612.0,RICAURTE,RESIDENCIAL_ESTRATO3,TECNOLOGIA_FIJA,60,6,2

In [ ]:
# Supongamos que tu DataFrame se llama 'df'
df.to_csv('/content/drive/MyDrive/Notebooks_Clase_2/content/producto_de_datos/DATOS_ORGANIZADOS.csv', index=False)